### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by FerDR89** [ale-strada/m7-dwf-desafio#1]
Buenas Ale, que bueno que hayas llegado hasta acá!

Estuve revisando el desafío y no me estaría tomando la modificación de la password y después de eso se rompe cuando quiero cerrar sesión, te dejo el error:

![image](https://user-images.githubusercontent.com/74626765/183899105-cba0dbb0-6b5d-44d0-a47f-c9e20f41cab1.png)

Otra cosa que noté es que cuando entras a "mis mascotas" el título primero renderiza "undefined" y despues se vuelve a renderizar con  "mis mascotas reportadas".

Cuando quiero reportar una mascota, la ubicación de Mapbox me esta tomando mi "ubicación más cercana" por más que ponga cualquier sitio

![image](https://user-images.githubusercontent.com/74626765/183900386-ae04d77c-20dd-41bc-8757-ab4bda5495dc.png)

Traté de publicar una mascota y cuando lo hago me redirige a "mis mascotas reportadas" pero no me muestra la mascota que reporte. Por lo que vi en network te esta fallando el endpoint /pets con un status 503

**Comment by ale-strada** [comment]
Hola Fer. Gracias por revisar el desafío. Me puse a ver las fallas que me marcas y en parte es xq las Pages no se recargan bien. no se si será el router o alguna otra cosa, probé recargando cada tanto con F5 y no me tira tantos errores, lo que no funciona es el cambio de password. ya lo reviso bien. En cuanto a la ubicación, hay que hacer click sobre el mapa para marcarla, el input de abajo es solo para agregar un dato mas, no lo habilite como buscador.
