### ISSUE TITLE
Review #2

### ISSUE THREAD

**Issue by Alvax10** [ale-strada/m7-dwf-desafio#2]
Buenass ale, como va? El desafío visualmente está hermoso! Pero tuve algunos problemitas, mirá:

1- Una vez registrado y logueado, quise ir a mis mascotas y la consola me tiraba error de que no podía leer mi email:
![Captura desde 2022-08-13 08-23-54](https://user-images.githubusercontent.com/64299010/184487163-c9d2bd6d-f52d-4903-8509-70e9059838e2.png)

2- Cuando traté de reportar una mascota, me tiró otro error:
![Captura desde 2022-08-13 08-24-51](https://user-images.githubusercontent.com/64299010/184488432-c6d1ada6-5129-4b64-95a8-5e9e59b9685d.png)

3- Por último te dejo una librería que capaz te pueda interesar, se llama `sweetalerts`, veo que tu página tiene un estilo muy lindo y capaz el `alert()` básico de js no queda bien con el diseño que tenés, está librería te deja poner alertas que ya están diseñadas para ajustarse al medio de la pantalla y se ven más lindas! Esto solo es un extra pero podes pegarle una ojeada a su página si te interesa como es y como funciona! 🙌🏻

**Comment by ale-strada** [comment]
Hola Alva.. cómo andas?? Gracias x ver El desafío. La verdad es q ya llevo un rato renegando co ese error y no se que es. Son 3 páginas que lo tienen y no sé cómo arreglarlo. Creo q no sé recargan bien las páginas xq si estás en la app y recargas la página manualmente cuando aparece ese error todo sigue funcionando bien

**Comment by ale-strada** [comment]
Yo lo subí así xq entendía que en este desafío lo importante es el backend ya que al front hay q rehacerlo..

**Comment by Alvax10** [comment]
Buenas ale, a pesar de que el front end no sea el fuerte de la webapp, igualmente tiene que estar funcional, como el resto de la página, saludos!

**Comment by Alvax10** [comment]
Si no sabé como solucionar el error del back pasate por el discord y lo hablamos!

**Comment by amunozdev** [comment]
Buenas Ale, muy bueno tu laburo, recién estaba testeando y me sucede lo mismo que a Alva lo más probable que es que la data del state se esté pisando por algún subscribe, pensá que cada subscribe va pusheando callbacks a un array y cada vez que se ejecuta setState, se ejecutan todos esos callbacks, por eso hay que tener cuidado con los subscribes.

Cada vez que se setea el state consologea cada `cb` del for y vas a saber que está sucediendo:
![Captura desde 2022-08-16 14-58-20](https://user-images.githubusercontent.com/77214476/184947503-aed57fae-510a-4066-9773-4a1314e60538.png)

Por otra parte, el subscribe en la page `sing-up` que función cumple?
![Captura desde 2022-08-16 14-57-40](https://user-images.githubusercontent.com/77214476/184947741-90fe5247-924d-41d1-b466-94b32404adba.png)

**Comment by ale-strada** [comment]
hola @Alvax10  y @alexismunoz1 como andan?? gracias x las observaciones!! estuve un par de dias sin compu pero ya esta andando de nuevo, ahora arranco a corregir esas cosas 💪. Si se complica estare molestando x el discord jaja

**Comment by FerDR89** [comment]
Buenas!
Al app quedo totalmente funcional, felicitaciones!

Hay algunas cosas del front que se pueden mejorar pero eso ya quedara para el mod que viene (tamañano fuente x ej).
Lo que si fijate que acá el componente no estaría funcionando como entiendo que quisiste hacer que en base lo que le llega del BE muestre un title u otro

![image](https://user-images.githubusercontent.com/74626765/185409403-49ebf989-6399-48a3-b453-4c7666a15ac7.png)

Éxitos en el próximo módulo!!!

**Comment by ale-strada** [comment]
Gracias @FerDR89! lo voy a tener en cuenta para el proximo desafio.
